# This is a basic workflow to help you get started with Actions

name: CI

on: 
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: ls | grep '^\!'
